import {useState} from 'react';
import ExportGuide from './ExportGuide';
import {connectFolder,resumeSync,pauseSync,folderSupported,useSyncStatus} from './folder-sync';
import {Icon} from './icons';
import {copy,type Project} from './model';
import {backup,download,markdownZip,thoughtHtml,safe,exportStats} from './export';
type Format='html'|'markdown'|'backup';
export default function ExportPanel({project,board,readOnly,onRestore,onNotice}:{project:Project;board:string;readOnly:boolean;onRestore:()=>void;onNotice:(message:string)=>void}){
 const [scope,setScope]=useState<'board'|'workspace'>('board'),[format,setFormat]=useState<Format>('html'),[tab,setTab]=useState<'files'|'sync'|'import'>('files'),[busy,setBusy]=useState(false),[guide,setGuide]=useState(false),[result,setResult]=useState('');const syncStatus=useSyncStatus(project.id);
 const folderAction=async(action:'connect'|'sync'|'pause')=>{setBusy(true);try{if(action==='connect')await connectFolder(copy(project));else if(action==='sync')await resumeSync(copy(project));else await pauseSync(project.id);}catch(e){const error=e as Error;if(error.name!=='AbortError')onNotice(['SecurityError','NotAllowedError'].includes(error.name)?'浏览器未允许文件夹写入，请在 Chrome / Edge 独立窗口打开本站后重试。':error.message||'无法连接文件夹，请使用下载导出');}finally{setBusy(false);}};
 const root=format==='backup'||scope==='workspace'?project.rootId:board,stats=exportStats(project,root),connected=!syncStatus.startsWith('尚未'),paused=syncStatus.includes('暂停'),supported=folderSupported();
 const run=async()=>{setBusy(true);setResult('');try{const snapshot=copy(project),name=safe(snapshot.boards[root].title),filename=format==='html'?`${name}-思路文档.html`:format==='markdown'?`${name}-Markdown.zip`:`${safe(snapshot.boards[snapshot.rootId].title)}-完整备份.json`;if(format==='html')download(new Blob([thoughtHtml(snapshot,root)],{type:'text/html;charset=utf-8'}),filename);else if(format==='markdown')download(await markdownZip(snapshot,root),filename);else download(backup(snapshot),filename);setResult(`已生成 ${filename}，请在浏览器下载中查看。`);onNotice('导出文件已生成');}catch{onNotice('导出失败，请重试');}finally{setBusy(false);}};
 return <div className="export-panel"><div className="export-heading"><div><span className="eyebrow">导出与备份</span><h2>{guide?'导出使用手册':tab==='import'?'导入工作台':'把思路带走'}</h2></div><button title="导出使用手册" aria-expanded={guide} onClick={()=>setGuide(!guide)}><Icon name="help" size={21}/></button></div>{guide?<><ExportGuide/><button className="soft-button" onClick={()=>setGuide(false)}><Icon name="back" size={15}/>返回导出</button></>:<>
 <div className="panel-tabs" role="tablist" aria-label="导出方式"><button role="tab" aria-selected={tab==='files'} onClick={()=>setTab('files')}>导出文件</button><button role="tab" aria-selected={tab==='sync'} onClick={()=>setTab('sync')}>自动同步</button><button role="tab" aria-selected={tab==='import'} onClick={()=>setTab('import')}>导入备份</button></div>
 {tab==='files'?<section role="tabpanel" aria-label="导出文件">
 <div className="export-options" role="radiogroup" aria-label="文件格式">{([{id:'html',icon:'book',title:'思路文档',detail:'离线阅读与回顾 · HTML，可打印为 PDF'},{id:'markdown',icon:'note',title:'Markdown + 表格 CSV',detail:'继续写作 · 可放入 Obsidian，含图片与附件'},{id:'backup',icon:'folder',title:'完整工作台备份',detail:'恢复画布 · 保留全部布局、外观与内容'}] as const).map(item=><button key={item.id} role="radio" aria-checked={format===item.id} disabled={busy} onClick={()=>{setFormat(item.id);setResult('');}}><span className="export-format-icon"><Icon name={item.icon} size={21}/></span><span><strong>{item.title}</strong><small>{item.detail}</small></span><span className="format-radio"/></button>)}</div>
 <div className="export-range"><label>包含内容</label>{format==='backup'?<div className="backup-scope"><Icon name="folder" size={15}/>整个工作台 <small>备份始终包含所有画板</small></div>:<div className="export-scope" aria-label="导出范围"><button disabled={busy} aria-pressed={scope==='board'} onClick={()=>{setScope('board');setResult('');}}>当前画板及子画板</button><button disabled={busy} aria-pressed={scope==='workspace'} onClick={()=>{setScope('workspace');setResult('');}}>整个工作台</button></div>}<p className="export-summary">{stats.boards} 张画板 · {stats.cards} 个内容 · {stats.openTasks} 项未完成待办</p></div>
 <button className="primary export-submit" disabled={busy} onClick={()=>void run()}><Icon name="download" size={17}/>{busy?'正在生成…':`导出${format==='html'?'思路文档':format==='markdown'?' Markdown 包':'完整备份'}`}</button>
 <div className="export-result" role="status">{result|| (format==='backup'?'此文件可用于恢复整个工作台。':'阅读文件不包含可恢复布局；留档请另存完整备份。')}</div>
 </section>:tab==='import'?<section className="import-panel" role="tabpanel" aria-label="导入备份"><div className="import-symbol"><Icon name="upload" size={30}/></div><h3>找回之前的思考空间</h3><p>选择从枝间导出的完整工作台备份（.json），恢复内容、附件、布局与外观。</p><button className="primary" disabled={readOnly||busy} onClick={onRestore}><Icon name="upload" size={17}/>选择备份文件</button><div className="import-details"><span>导入后新建独立工作台，保留当前内容。</span><span>思路文档 HTML、Markdown ZIP 与 CSV 是阅读导出文件，不能用于恢复画布。</span></div></section>:<section className="folder-sync" role="tabpanel" aria-label="自动同步"><div className="sync-intro"><span><Icon name="folder" size={25}/></span><h3>在知识库里保留一份</h3><p>选一个本地文件夹或 Obsidian 知识库。页面打开时，整个工作台会自动更新到独立目录。</p></div><div className="sync-status" role="status">{syncStatus}</div>{!supported&&<p>当前浏览器不支持选择文件夹，请用桌面 Chrome / Edge，或下载 Markdown 包。</p>}<div className="sync-actions">{!connected?<button className="primary" disabled={readOnly||busy||!supported} onClick={()=>void folderAction('connect')}>选择同步文件夹</button>:<><button className="primary" disabled={readOnly||busy||!supported} onClick={()=>void folderAction('sync')}>{paused?'恢复同步':syncStatus.includes('授权')?'重新授权':'立即同步'}</button><button disabled={readOnly||busy||!supported} onClick={()=>void folderAction(paused?'connect':'pause')}>{paused?'更换文件夹':'暂停同步'}</button>{!paused&&<button disabled={readOnly||busy||!supported} onClick={()=>void folderAction('connect')}>更换文件夹</button>}</>}</div><p className="sync-boundary">单向保存 Markdown、附件、CSV 与完整备份。外部编辑冲突会暂停；关闭页面后不运行。</p></section>}
 {tab!=='import'&&<footer className="export-footer"><span>已有完整备份？</span><button disabled={busy} onClick={()=>setTab('import')}><Icon name="upload" size={15}/>导入备份</button></footer>}
 </>}</div>;
}
