export {thoughtHtml,exportStats} from './thought-export';
import {progressLabels} from './planning';
import {thoughtHtml,tableCsv,tableMarkdown,thoughtSummary} from './thought-export';
import JSZip from 'jszip';
import {descendants,validate,type Project,type Card} from './model';
export const safe=(s:string)=>s.replace(/[\\/:*?"<>|\u0000-\u001f]/g,'_').slice(0,60)||'未命名';
const text=(s:string)=>s.replace(/[\[\]\\]/g,'\\$&').replace(/\n/g,' ');
export const fileName=(p:Project,id:string)=>`${safe(p.boards[id].title)}-${safe(id)}.md`;
function assetName(p:Project,id:string){const a=p.assets[id];return `${safe(id)}.${a?.mime==='image/jpeg'?'jpg':a?.mime==='image/webp'?'webp':a?.mime==='image/gif'?'gif':'png'}`;}
export function markdown(p:Project,boardId:string,included=descendants(p,boardId),nameFor=(id:string)=>fileName(p,id)):string{const all=Object.values(p.cards).filter(n=>n.boardId===boardId);const sorted=(ns:Card[])=>ns.sort((a,b)=>a.y-b.y||a.x-b.x||a.id.localeCompare(b.id));const render=(n:Card):string=>{let s=`<a id="${n.id}"></a>\n\n`;if(n.kind==='column'){return s+`## ${text(n.title)}\n\n`+all.filter(c=>c.columnId===n.id).sort((a,b)=>a.order-b.order).map(render).join('\n');}if(n.kind==='board')return s+`## [${text(n.title)}](${encodeURI(nameFor(n.target!))})\n\n`;if(n.title)s+=`### ${text(n.title)}\n\n`;if(n.focus)s+='**研究重点**\n\n';if(n.kind==='image')s+=`![${text(n.body||n.title)}](../assets/${assetName(p,n.assetId!)})\n\n`;else if(n.kind==='todo')s+=(n.tasks||[]).map(t=>`${'  '.repeat(t.indent)}- [${t.done?'x':' '}] ${t.text.replace(/\n/g,' ')}`).join('\n')+'\n\n';else if(n.kind==='progress'&&n.progress){s+=`**${progressLabels[n.progress.status]} · ${n.progress.percent}%**${n.progress.due?` · 截止 ${n.progress.due}`:''}\n\n${n.body}\n\n`;}else if(n.kind==='table'&&n.table){s+=tableMarkdown(n.table)+'\n\n';}else if(n.kind==='link'){if(n.assetId)s+=`![${text(n.title||'链接封面')}](../assets/${assetName(p,n.assetId)})\n\n`;s+=`[${text(n.title||n.url||'链接')}](${(n.url||'').replace(/\)/g,'%29')})\n\n${n.body}\n\n`;}else s+=n.body+'\n\n';return s;};let s=`# ${text(p.boards[boardId].title)}\n\n`+sorted(all.filter(n=>!n.columnId)).map(render).join('');const edges=Object.values(p.edges).filter(e=>p.cards[e.from]?.boardId===boardId||p.cards[e.to]?.boardId===boardId);if(edges.length){s+='## 关系\n\n';const ref=(id:string)=>{const n=p.cards[id];return included.has(n.boardId)?`[${text(n.title||n.body.slice(0,24)||n.kind)}](${encodeURI(nameFor(n.boardId))}#${n.id})`:`${text(n.title||n.kind)}（范围外，${id}）`;};s+=edges.map(e=>`- ${ref(e.from)} ${e.arrow?'→':'—'} ${ref(e.to)}${e.label?`：${e.label}`:''}`).join('\n');}return s;}
export function workspaceFiles(p:Project,root:string,stable=false){const files=new Map<string,string|Uint8Array>(),ids=descendants(p,root),assets=new Set<string>(),nameFor=(id:string)=>stable?`board-${safe(id)}.md`:fileName(p,id);for(const id of ids){files.set(`boards/${nameFor(id)}`,(stable?`---\naliases: ${JSON.stringify([p.boards[id].title])}\nzhijian_board_id: ${JSON.stringify(id)}\n---\n\n`:'')+markdown(p,id,ids,nameFor));for(const n of Object.values(p.cards))if(n.boardId===id){if(n.assetId)assets.add(n.assetId);if(n.table)files.set(`tables/table-${safe(n.id)}.csv`,tableCsv(n.table));}}for(const id of assets){const a=p.assets[id];if(a)files.set(`assets/${assetName(p,id)}`,Uint8Array.from(atob(a.data.split(',')[1]),c=>c.charCodeAt(0)));}files.set('思路回顾.md',thoughtSummary(p,root));files.set('README.md',`# ${p.boards[root].title}\n\n[打开画板文档](boards/${encodeURI(nameFor(root))})\n\n[思路回顾与下一步](思路回顾.md)\n\n表格 CSV 在 tables/，图片在 assets/。此文件夹可放入 Obsidian 知识库。生成文件为画布的单向镜像，外部修改会暂停同步；个人补充笔记请放在生成目录外。\n\n完整备份 JSON 用于恢复；删除或改名后的旧文件保留，以上目录链接以当前内容为准。`);files.set('export-report.md',`# 导出报告\n\n画板：${ids.size}\n附件：${assets.size}\n\n默认阅读顺序为从上到下、从左到右；栏内使用原顺序。二维坐标、颜色与线形请用完整备份恢复。`);if(stable){files.set('思路文档.html',thoughtHtml(p,root));files.set('完整备份.json',JSON.stringify(p));}return files;}
export async function markdownZip(p:Project,root:string){const zip=new JSZip();for(const [path,data] of workspaceFiles(p,root))zip.file(path,data);return zip.generateAsync({type:'blob'});}
export function download(blob:Blob,name:string){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
export function backup(p:Project){return new Blob([JSON.stringify(p)],{type:'application/json'});}
export async function readBackup(file:File){if(file.size>150*1024*1024)throw Error('备份超过 150MB，暂不支持导入');const p=JSON.parse(await file.text());validate(p);return p as Project;}
