export type Kind='note'|'todo'|'link'|'image'|'board'|'column'|'progress'|'table';
export type View={x:number;y:number;z:number};
export type Task={id:string;text:string;done:boolean;indent:number};
export type Progress={status:'planned'|'active'|'blocked'|'done';percent:number;due:string};
export type TableData={columns:string[];rows:{id:string;cells:string[]}[]};
export type Card={id:string;boardId:string;kind:Kind;x:number;y:number;w:number;title:string;body:string;color:string;icon:string;fill?:string;iconStyle?:'outline'|'filled';iconTone?:'dark'|'white';showIcon?:boolean;accentExplicit?:boolean;columnId?:string;order:number;target?:string;url?:string;assetId?:string;ratio?:number;imageFrame?:boolean;tasks?:Task[];progress?:Progress;table?:TableData;collapsed?:boolean;focus?:boolean};
export type Board={id:string;parentId:string|null;title:string;view:View;theme?:string};
export type Edge={id:string;from:string;to:string;label:string;curve:number;dashed:boolean;arrow:boolean;width?:number;color?:string;startArrow?:boolean;bend?:{x:number;y:number}};
export type Asset={id:string;name:string;mime:string;data:string};
export type Project={version:1;id:string;rootId:string;boards:Record<string,Board>;cards:Record<string,Card>;edges:Record<string,Edge>;assets:Record<string,Asset>;updatedAt:number};
export const uid=()=>crypto.randomUUID();
export const colors=['#51b9f7','#ffd44f','#60d6c4','#ff914d','#f56ecb','#b5a0f3','#69717e'];
export const copy=(p:Project):Project=>({...p,boards:Object.fromEntries(Object.entries(p.boards).map(([k,b])=>[k,{...b,view:{...b.view}}])),cards:Object.fromEntries(Object.entries(p.cards).map(([k,n])=>[k,{...n,tasks:n.tasks?.map(t=>({...t})),progress:n.progress?{...n.progress}:undefined,table:n.table?{columns:[...n.table.columns],rows:n.table.rows.map(r=>({...r,cells:[...r.cells]}))}:undefined}])),edges:Object.fromEntries(Object.entries(p.edges).map(([k,e])=>[k,{...e}])),assets:{...p.assets}});
export function addCard(p:Project,boardId:string,kind:Kind,x:number,y:number):Card{const n:Card={id:uid(),boardId,kind,x,y,w:kind==='board'?140:kind==='column'?280:kind==='table'?360:kind==='progress'?280:248,title:kind==='board'?'新画板':kind==='column'?'新分栏':kind==='todo'?'待办清单':kind==='progress'?'新的目标':kind==='table'?'对比表格':'',body:'',color:kind==='board'?colors[0]:'',icon:kind==='board'?'board':'note',order:Date.now()};if(kind==='progress')n.progress={status:'planned',percent:0,due:''};if(kind==='table')n.table={columns:['项目','说明','下一步'],rows:[{id:uid(),cells:['','','']},{id:uid(),cells:['','','']}]};if(kind==='image')n.imageFrame=true;if(kind==='todo')n.tasks=[{id:uid(),text:'',done:false,indent:0}];if(kind==='board'){n.iconStyle='outline';n.target=uid();p.boards[n.target]={id:n.target,parentId:boardId,title:n.title,theme:p.boards[boardId].theme,view:{x:100,y:100,z:1}};}p.cards[n.id]=n;return n;}
export function height(n:Card):number{if(n.kind==='board')return 130;if(n.kind==='progress')return 190;if(n.kind==='table')return 104+(n.table?.rows.length||2)*34;if(n.kind==='image'){const copy=(n.title?26:0)+(n.body?40:0)+(n.title||n.body?10:0),frame=n.imageFrame===false?0:28,inner=Math.max(1,n.w-frame-2);return inner/(n.ratio||1)+copy+frame+7;}if(n.kind==='todo')return 48+(n.tasks||[]).reduce((a,t)=>a+Math.max(28,Math.ceil(t.text.length/Math.max(8,Math.floor((n.w-54-t.indent*18)/14)))*22+5),0);if(n.kind==='link')return 74+Math.max(28,Math.ceil(n.body.length/Math.max(8,(n.w-28)/14))*22);return 44+Math.max(30,Math.ceil(n.body.split('\n').reduce((a,l)=>a+Math.max(1,Math.ceil(l.length/Math.max(8,(n.w-28)/14))),0))*22);}
export type Rect={x:number;y:number;w:number;h:number};
export function layout(p:Project,boardId:string,measured:Record<string,{w:number;h:number}>={}):Record<string,Rect>{const size=(n:Card)=>measured[n.id]&&Math.abs(measured[n.id].w-n.w)<3?measured[n.id].h:height(n);const out:Record<string,Rect>={};const cards=Object.values(p.cards).filter(n=>n.boardId===boardId);for(const n of cards.filter(n=>!n.columnId)){if(n.kind!=='column'){out[n.id]={x:n.x,y:n.y,w:n.w,h:size(n)};continue;}let y=n.y+76,boardColumn=0;const slots=Math.max(1,Math.floor((n.w-12)/124));const kids=cards.filter(c=>c.columnId===n.id).sort((a,b)=>a.order-b.order);const flushBoards=()=>{if(boardColumn){y+=130+14;boardColumn=0;}};if(!n.collapsed)for(let i=0;i<kids.length;i++){const c=kids[i],next=kids[i+1],canGrid=c.kind==='board';if(canGrid){const w=Math.floor((n.w-24-(slots-1)*12)/slots);out[c.id]={x:n.x+12+boardColumn*(w+12),y,w,h:size({...c,w})};boardColumn++;if(boardColumn===slots||next?.kind!=='board')flushBoards();continue;}flushBoards();const w=n.w-24;out[c.id]={x:n.x+12,y,w,h:size({...c,w})};y+=out[c.id].h+14;}flushBoards();out[n.id]={x:n.x,y:n.y,w:n.w,h:n.collapsed?84:Math.max(174,y-n.y+8)};}return out;}
export function pathTo(p:Project,id:string):Board[]{const result:Board[]=[];const seen=new Set<string>();while(p.boards[id]&&!seen.has(id)){seen.add(id);const b=p.boards[id];result.unshift(b);if(!b.parentId)break;id=b.parentId;}return result;}
export function descendants(p:Project,id:string):Set<string>{const ids=new Set([id]);const queue=[id];while(queue.length){const parent=queue.shift();for(const b of Object.values(p.boards))if(b.parentId===parent&&!ids.has(b.id)){ids.add(b.id);queue.push(b.id);}}return ids;}
export function selectionWithChildren(p:Project,ids:string[]):Set<string>{const out=new Set(ids);for(const n of Object.values(p.cards))if(n.columnId&&out.has(n.columnId))out.add(n.id);return out;}
export function removeCards(p:Project,ids:string[]){const gone=new Set(ids);const before=Object.fromEntries(Object.keys(p.boards).map(id=>[id,layout(p,id)]));for(const id of ids){const n=p.cards[id];if(n?.kind==='column')for(const c of Object.values(p.cards))if(c.columnId===id){const r=before[c.boardId][c.id];c.columnId=undefined;if(r){c.x=r.x;c.y=r.y;}}if(n?.target){const bs=descendants(p,n.target);for(const b of bs)delete p.boards[b];for(const c of Object.values(p.cards))if(bs.has(c.boardId))gone.add(c.id);}}for(const id of gone)delete p.cards[id];for(const e of Object.values(p.edges))if(gone.has(e.from)||gone.has(e.to))delete p.edges[e.id];}
export function splitSelection(p:Project,boardId:string,ids:string[],title:string):string{const selected=selectionWithChildren(p,ids);const rs=layout(p,boardId);const nodes=[...selected].map(id=>p.cards[id]).filter(n=>n?.boardId===boardId);if(!nodes.length)throw Error('请选择当前画板中的内容');const x=Math.min(...nodes.map(n=>rs[n.id]?.x??n.x));const y=Math.min(...nodes.map(n=>rs[n.id]?.y??n.y));const entry=addCard(p,boardId,'board',x,y);entry.title=title;p.boards[entry.target!].title=title;for(const n of nodes){const r=rs[n.id];n.boardId=entry.target!;n.x=(r?.x??n.x)-x+60;n.y=(r?.y??n.y)-y+60;if(n.columnId&&!selected.has(n.columnId))n.columnId=undefined;if(n.target)p.boards[n.target].parentId=entry.target!;}return entry.id;}
export function moveIntoBoard(p:Project,ids:string[],target:string){if(!p.boards[target])throw Error('画板不存在');const selected=selectionWithChildren(p,ids);for(const id of selected){const n=p.cards[id];if(n?.target&&descendants(p,n.target).has(target))throw Error('不能把画板放入自己的子画板');}const existing=Object.entries(layout(p,target)).filter(([id])=>!selected.has(id)).map(([,r])=>r);let x=60,y=existing.length?Math.max(...existing.map(r=>r.y+r.h))+40:60,rowHeight=0;for(const id of selected){const n=p.cards[id];if(!n)continue;n.boardId=target;if(!n.columnId||!selected.has(n.columnId)){n.columnId=undefined;if(x>60&&x+n.w>1000){x=60;y+=rowHeight+36;rowHeight=0;}n.x=x;n.y=y;x+=n.w+36;rowHeight=Math.max(rowHeight,height(n));}if(n.target)p.boards[n.target].parentId=target;}}
export function duplicateCards(p:Project,ids:string[]):string[]{
const selected=selectionWithChildren(p,ids);const boardIds=new Set<string>();
for(const id of selected){const n=p.cards[id];if(n?.target)for(const b of descendants(p,n.target))boardIds.add(b);}
for(const n of Object.values(p.cards))if(boardIds.has(n.boardId))selected.add(n.id);
const positions=Object.fromEntries([...new Set([...selected].map(id=>p.cards[id]?.boardId).filter(Boolean) as string[])].map(id=>[id,layout(p,id)]));
const cardMap=new Map([...selected].map(id=>[id,uid()]));const boardMap=new Map([...boardIds].map(id=>[id,uid()]));
for(const id of boardIds){const b=p.boards[id];const newId=boardMap.get(id)!;p.boards[newId]={...b,id:newId,parentId:boardMap.get(b.parentId!)||b.parentId,view:{...b.view}};}
for(const id of selected){const n=p.cards[id];if(!n)continue;const nested=boardIds.has(n.boardId),parentCopied=!!(n.columnId&&cardMap.has(n.columnId)),r=positions[n.boardId]?.[n.id];const c:Card={...n,id:cardMap.get(id)!,boardId:boardMap.get(n.boardId)||n.boardId,x:nested||parentCopied?n.x:(r?.x??n.x)+28,y:nested||parentCopied?n.y:(r?.y??n.y)+28,tasks:n.tasks?.map(t=>({...t,id:uid()})),progress:n.progress?{...n.progress}:undefined,table:n.table?{columns:[...n.table.columns],rows:n.table.rows.map(r=>({id:uid(),cells:[...r.cells]}))}:undefined,target:n.target?boardMap.get(n.target):undefined,columnId:parentCopied?cardMap.get(n.columnId!):undefined};p.cards[c.id]=c;}
for(const e of Object.values(p.edges))if(cardMap.has(e.from)&&cardMap.has(e.to)){const c={...e,id:uid(),from:cardMap.get(e.from)!,to:cardMap.get(e.to)!};p.edges[c.id]=c;}
return ids.map(id=>cardMap.get(id)!).filter(Boolean);
}
export function projected(p:Project,cardId:string,boardId:string):string|undefined{let n=p.cards[cardId];if(!n)return; if(n.boardId===boardId)return cardId;const seen=new Set<string>();let b=n.boardId;while(p.boards[b]&&!seen.has(b)){seen.add(b);const entry=Object.values(p.cards).find(c=>c.target===b);if(!entry)return;if(entry.boardId===boardId)return entry.id;b=entry.boardId;}return;}
export function validate(v:unknown):asserts v is Project{const p=v as Project;if(!p||p.version!==1||typeof p.id!=='string'||!p.boards||!p.cards||!p.edges||!p.assets||!p.boards[p.rootId])throw Error('备份格式或版本不支持');const kinds=['note','todo','link','image','board','column','progress','table'];for(const [id,b] of Object.entries(p.boards)){if(b.id!==id||typeof b.title!=='string'||!b.view||![b.view.x,b.view.y,b.view.z].every(Number.isFinite)||b.view.z<=0)throw Error('画板数据无效');if(id===p.rootId&&b.parentId!==null)throw Error('首页归属无效');if(id!==p.rootId&&(!b.parentId||!p.boards[b.parentId]))throw Error('父画板缺失');const seen=new Set<string>();let cur:string|null=id;while(cur){if(seen.has(cur))throw Error('画板层级存在循环');seen.add(cur);cur=p.boards[cur]?.parentId??null;}}
for(const [id,n] of Object.entries(p.cards)){if(n.fill!==undefined&&n.fill!==''&&(typeof n.fill!=='string'||!/^#[\da-f]{6}$/i.test(n.fill)))throw Error('背景颜色无效');if(n.iconTone!==undefined&&!['dark','white'].includes(n.iconTone))throw Error('图标颜色无效');if(n.iconStyle!==undefined&&!['outline','filled'].includes(n.iconStyle))throw Error('图标样式无效');if(n.accentExplicit!==undefined&&typeof n.accentExplicit!=='boolean')throw Error('色条设置无效');if(n.showIcon!==undefined&&typeof n.showIcon!=='boolean')throw Error('卡片图标设置无效');if(n.imageFrame!==undefined&&typeof n.imageFrame!=='boolean')throw Error('图片留白设置无效');if(n.id!==id||!p.boards[n.boardId]||!kinds.includes(n.kind)||![n.x,n.y,n.w,n.order].every(Number.isFinite)||n.w<40||n.w>4000||typeof n.body!=='string'||typeof n.title!=='string'||typeof n.icon!=='string'||typeof n.color!=='string')throw Error('卡片数据无效');if(n.columnId){const c=p.cards[n.columnId];if(!c||c.kind!=='column'||c.boardId!==n.boardId||n.kind==='column')throw Error('分栏归属无效');}if(n.kind==='board'&&(!n.target||p.boards[n.target]?.parentId!==n.boardId))throw Error('子画板入口无效');if((n.kind==='image'||n.kind==='link'&&n.assetId)&&(!n.assetId||!p.assets[n.assetId]))throw Error('图片附件缺失');if(n.kind==='progress'&&(!n.progress||!['planned','active','blocked','done'].includes(n.progress.status)||!Number.isFinite(n.progress.percent)||n.progress.percent<0||n.progress.percent>100||typeof n.progress.due!=='string'||(n.progress.due!==''&&!/^\d{4}-\d{2}-\d{2}$/.test(n.progress.due))))throw Error('进度数据无效');if(n.kind==='table'&&(!n.table||!Array.isArray(n.table.columns)||n.table.columns.length<1||n.table.columns.length>8||n.table.columns.some(c=>typeof c!=='string')||!Array.isArray(n.table.rows)||n.table.rows.length<1||n.table.rows.length>100||new Set(n.table.rows.map(r=>r.id)).size!==n.table.rows.length||n.table.rows.some(r=>typeof r.id!=='string'||!Array.isArray(r.cells)||r.cells.length!==n.table!.columns.length||r.cells.some(c=>typeof c!=='string'))))throw Error('表格数据无效');if(n.tasks&&(!Array.isArray(n.tasks)||n.tasks.some(t=>typeof t.text!=='string'||typeof t.done!=='boolean'||!Number.isFinite(t.indent)||t.indent<0||t.indent>4)))throw Error('清单数据无效');}
for(const b of Object.values(p.boards)){if(b.theme!==undefined&&typeof b.theme!=='string')throw Error('画布主题无效');if(b.id!==p.rootId&&Object.values(p.cards).filter(c=>c.target===b.id).length!==1)throw Error('画板入口重复或缺失');}for(const [id,e] of Object.entries(p.edges))if((e.color!==undefined&&!/^#[\da-f]{6}$/i.test(e.color))||(e.startArrow!==undefined&&typeof e.startArrow!=='boolean')||(e.bend!==undefined&&(!Number.isFinite(e.bend.x)||!Number.isFinite(e.bend.y))))throw Error('连线外观无效');else if(e.id!==id||!p.cards[e.from]||!p.cards[e.to]||typeof e.label!=='string'||!Number.isFinite(e.curve)||typeof e.arrow!=='boolean'||typeof e.dashed!=='boolean'||(e.width!==undefined&&(!Number.isFinite(e.width)||e.width<1||e.width>5)))throw Error('连线无效');for(const [id,a] of Object.entries(p.assets))if(a.id!==id||!/^data:image\/(png|jpeg|webp|gif);base64,/.test(a.data)||typeof a.name!=='string')throw Error('不支持的图片数据');}
export function seed():Project{const root=uid();const p:Project={version:1,id:uid(),rootId:root,boards:{[root]:{id:root,parentId:null,title:'从一个问题开始',view:{x:40,y:40,z:1}}},cards:{},edges:{},assets:{},updatedAt:Date.now()};const note=addCard(p,root,'note',20,24);note.title='01  写下你想理清的问题';note.body='一个想法、一次选择，或一件还没想明白的事。先写下来，再把资料、问题与下一步放在一起。\n双击卡片编辑正文；点击正文链接打开参考。';note.w=900;
const todo=addCard(p,root,'todo',630,350);todo.title='03  试着推进一步';todo.tasks=[{id:uid(),text:'点开「产品探索」，拆出一个小问题',done:false,indent:0},{id:uid(),text:'拖动卡片，从圆点连出你的思路',done:false,indent:0},{id:uid(),text:'选一个下一步，标记为完成',done:false,indent:0}];todo.w=290;
const topics=[['产品探索','box',colors[0],80,180],['灵感收集','sparkles',colors[4],300,180],['视觉参考','palette',colors[2],520,180],['写作计划','pencil',colors[1],740,180]] as const;const entries:Card[]=[];for(const [title,icon,color,x,y]of topics){const n=addCard(p,root,'board',x,y);Object.assign(n,{title,icon,color});p.boards[n.target!].title=title;entries.push(n);}for(let i=0;i<entries.length-1;i++){const e:Edge={id:uid(),from:entries[i].id,to:entries[i+1].id,label:['拆出问题','收集线索','整理成表达'][i],curve:0,dashed:false,arrow:true};p.edges[e.id]=e;}
const idea=addCard(p,root,'note',20,580);idea.title='把你的思路带走';idea.body='导出思路文档回顾问题与关系，或导出 Markdown 继续写作。完整备份用于恢复布局。\n这是可编辑的示例；也可以从左上角创建空白工作台。';idea.w=900;const progress=addCard(p,root,'progress',320,350);progress.title='形成一个清晰的方向';progress.progress={status:'active',percent:25,due:''};progress.body='目标不必很大，先推进一小步。';const table=addCard(p,root,'table',20,350);table.w=290;table.title='02  比较几个方向';table.table={columns:['方向','值得探索的原因'],rows:[{id:uid(),cells:['方向 A','你最关心的问题']},{id:uid(),cells:['方向 B','另一种可能性']}]};
const board=entries[0].target!;p.boards[board].view={x:70,y:60,z:.9};const col=addCard(p,board,'column',20,20);col.title='产品想法';col.color=colors[0];const n1=addCard(p,board,'note',0,0);Object.assign(n1,{title:'我们想解决什么？',body:'把散落的资料和想法放到一个空间里。\n\n每个方向都可以继续展开，同时保留整体的脉络。',columnId:col.id,order:0});const n2=addCard(p,board,'todo',0,0);Object.assign(n2,{title:'下一步',columnId:col.id,order:1,tasks:[{id:uid(),text:'收集三个参考案例',done:false,indent:0},{id:uid(),text:'确定最值得深入的问题',done:false,indent:0}]});const subs=[['用户与场景','users',colors[4],420,100],['竞品参考','search',colors[1],670,100],['设计方向','brush',colors[2],920,100]] as const;let prev:Card|undefined;for(const [title,icon,color,x,y]of subs){const n=addCard(p,board,'board',x,y);Object.assign(n,{title,icon,color});p.boards[n.target!].title=title;if(prev){const e:Edge={id:uid(),from:prev.id,to:n.id,label:'',curve:0,dashed:false,arrow:true};p.edges[e.id]=e;}prev=n;}const guide=addCard(p,board,'note',435,355);guide.title='每个主题，都有下一层';guide.body='点击彩色图标进入子画板。\n用顶部路径返回，全局的位置会被记住。\n\n选中卡片，从右侧圆点拖出连线。';guide.w=400;
return p;}
