import {useLayoutEffect,useRef} from 'react';
import {Field} from './InlineCard';
import {Icon} from './icons';
import {uid,type Card} from './model';
import {addTableColumn,addTableRow,removeTableColumn,removeTableRow,progressLabels} from './planning';

type Props={card:Card;readOnly:boolean;onChange:(patch:Partial<Card>)=>void;onBoundary:()=>void;onEditing:(active:boolean)=>void;onMeasure?:(h:number,w:number)=>void};
export default function PlanningCard({card:n,readOnly,onChange,onBoundary,onEditing,onMeasure}:Props){
 const ref=useRef<HTMLDivElement>(null);
 useLayoutEffect(()=>{const el=ref.current;if(!el||!onMeasure)return;const measure=()=>{const parent=el.parentElement!,style=getComputedStyle(parent);onMeasure(Math.ceil(el.offsetHeight+parseFloat(style.borderTopWidth)+parseFloat(style.borderBottomWidth)),parent.clientWidth+2);};const observer=new ResizeObserver(measure);observer.observe(el);measure();return()=>observer.disconnect();},[onMeasure]);
 const table=n.table;
 const focusCell=(row:number,col:number)=>requestAnimationFrame(()=>ref.current?.querySelector<HTMLTextAreaElement>(`[data-cell="${row}-${col}"]`)?.focus());
 return <div ref={ref} className="planning-card" onFocus={()=>onEditing(true)} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node)){onBoundary();onEditing(false);}}}>
  <div className="inline-title-row">{n.showIcon&&<span className="inline-title-icon"><Icon name={n.icon} size={22} variant={n.iconStyle||'filled'}/></span>}<Field aria-label="卡片标题" className="inline-title" placeholder="添加标题" value={n.title} readOnly={readOnly} onChange={e=>onChange({title:e.target.value})}/></div>
  {n.kind==='progress'&&n.progress&&<div className="progress-content">
   <div className="progress-heading"><select aria-label="进度状态" value={n.progress.status} disabled={readOnly} onChange={e=>{const status=e.target.value as NonNullable<Card['progress']>['status'];onChange({progress:{...n.progress!,status,percent:status==='done'?100:status==='planned'?0:n.progress!.percent}});}}>{Object.entries(progressLabels).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select><label className="progress-percent"><input aria-label="完成比例" type="number" min={0} max={100} value={n.progress.percent} readOnly={readOnly} onChange={e=>{const percent=Math.max(0,Math.min(100,Number(e.target.value)));onChange({progress:{...n.progress!,percent,status:percent===100?'done':n.progress!.status==='blocked'?'blocked':percent===0?'planned':'active'}});}}/><span>%</span></label></div>
   <div className="progress-track" role="progressbar" aria-label={n.title||'目标进度'} aria-valuenow={n.progress.percent} aria-valuemin={0} aria-valuemax={100}><span style={{width:n.progress.percent+'%'}}/></div>
   <label className="progress-due"><span>截止日期</span><input aria-label="截止日期" type="date" value={n.progress.due} readOnly={readOnly} onChange={e=>onChange({progress:{...n.progress!,due:e.target.value}})}/></label>
   <Field className="progress-note" aria-label="目标说明" placeholder="写下下一步或阻碍…" value={n.body} readOnly={readOnly} onChange={e=>onChange({body:e.target.value})}/>
  </div>}
  {n.kind==='table'&&table&&<><div className="table-scroll"><table className="editable-table" style={{minWidth:table.columns.length*85+19}}><thead><tr>{table.columns.map((column,col)=><th key={col}><Field aria-label={`列名 ${col+1}`} value={column} placeholder={`列 ${col+1}`} readOnly={readOnly} onChange={e=>onChange({table:{...table,columns:table.columns.map((v,i)=>i===col?e.target.value:v)}})}/>{!readOnly&&table.columns.length>1&&<button className="table-delete-column" aria-label={`删除第 ${col+1} 列`} onClick={()=>{onBoundary();onChange({table:removeTableColumn(table,col)});onBoundary();}}><Icon name="x" size={12}/></button>}</th>)}<th className="table-row-actions"/></tr></thead><tbody>{table.rows.map((row,r)=><tr key={row.id}>{row.cells.map((cell,col)=><td key={col}><Field data-cell={`${r}-${col}`} aria-label={`第 ${r+1} 行第 ${col+1} 列`} value={cell} readOnly={readOnly} onChange={e=>onChange({table:{...table,rows:table.rows.map(item=>item.id===row.id?{...item,cells:item.cells.map((v,i)=>i===col?e.target.value:v)}:item)}})} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing&&!readOnly){e.preventDefault();if(r===table.rows.length-1){if(table.rows.length>=100)return;onChange({table:addTableRow(table,uid())});}focusCell(r+1,col);}}}/></td>)}<td className="table-row-actions">{!readOnly&&table.rows.length>1&&<button aria-label={`删除第 ${r+1} 行`} onClick={()=>{onBoundary();onChange({table:removeTableRow(table,row.id)});onBoundary();}}><Icon name="x" size={12}/></button>}</td></tr>)}</tbody></table></div>{!readOnly&&<div className="table-actions"><button disabled={table.rows.length>=100} onClick={()=>{onBoundary();onChange({table:addTableRow(table,uid())});onBoundary();focusCell(table.rows.length,0);}}><Icon name="plus" size={14}/>添加行</button><button disabled={table.columns.length>=8} onClick={()=>{onBoundary();onChange({table:addTableColumn(table)});onBoundary();}}>添加列</button></div>}</>}
 </div>;
}
