import {useEffect,useState} from 'react';
import {Icon} from './icons';
import type {Project} from './model';
import {listProjects,restoreProject,purgeProjects} from './storage';
import {backup,download,safe} from './export';
const date=(p:Project)=>new Date(p.updatedAt).toLocaleDateString('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit'}).replaceAll('/','.');
export default function WorkspacePanel({current,activeProject,readOnly,onSwitch,onDelete,onNew,onNotice}:{current:string;activeProject:Project;readOnly:boolean;onSwitch:(p:Project)=>void;onDelete:(p:Project)=>Promise<void>;onNew:()=>void;onNotice:(s:string)=>void}){
 const [all,setAll]=useState<Project[]>([]),[trash,setTrash]=useState<Project[]>([]),[target,setTarget]=useState<Project>(),[purge,setPurge]=useState<{ids:string[];title:string}>(),[busy,setBusy]=useState(false),[showTrash,setShowTrash]=useState(false);
 const refresh=async()=>{setAll(await listProjects());setTrash(await listProjects(true));};useEffect(()=>{void refresh();},[]);
 const remove=async(exportFirst:boolean)=>{if(!target)return;setBusy(true);try{if(exportFirst)download(backup(target),`${safe(target.boards[target.rootId].title)}-完整备份.json`);await onDelete(target);setTarget(undefined);await refresh();}catch{onNotice('删除未完成，请重试');}finally{setBusy(false);}};
 const restore=async(p:Project)=>{setBusy(true);try{await restoreProject(p.id);await refresh();onNotice(`已恢复「${p.boards[p.rootId].title}」`);}catch{onNotice('恢复未完成，请重试');}finally{setBusy(false);}};
 const permanentlyDelete=async()=>{if(!purge)return;setBusy(true);try{await purgeProjects(purge.ids);await refresh();setPurge(undefined);onNotice('已永久删除，无法从回收站恢复');}catch(e){onNotice((e as Error).message||'删除未完成，请重试');await refresh();setPurge(undefined);}finally{setBusy(false);}};
 return <section className="workspace-panel"><header><span className="eyebrow">本地工作台</span><h2>{purge?'永久删除':target?'移入回收站':'你的思考空间'}</h2></header>{purge?<section className="workspace-purge" role="alertdialog" aria-label="确认永久删除"><div className="purge-symbol"><Icon name="trash" size={27}/></div><h3>{purge.title}</h3><p>将永久删除 {purge.ids.length} 个工作台及其中的画板、内容和附件，无法撤销或恢复。</p><p className="panel-footnote">已导出的备份和同步到本地文件夹的文件会保留。</p><div className="purge-actions"><button autoFocus disabled={busy} onClick={()=>setPurge(undefined)}>取消</button><button className="danger-button" disabled={readOnly||busy} onClick={()=>void permanentlyDelete()}>{busy?'正在删除…':'确认永久删除'}</button></div></section>:target?<section className="workspace-delete">
 <button className="panel-back" disabled={busy} onClick={()=>setTarget(undefined)}><Icon name="back" size={15}/>返回工作台</button>
 <div className="delete-workspace-summary"><Icon name="board" size={24}/><span><strong>{target.boards[target.rootId].title}</strong><small>{Object.keys(target.boards).length} 张画板 · {Object.keys(target.cards).length} 个内容</small></span></div>
 <p>工作台会移入本浏览器的回收站，可以恢复。建议先下载完整备份留档。</p>
 <details><summary>数据与文件会怎样处理？</summary><p>清除网站数据会丢失回收站内容。已同步到文件夹的文件保留，同步停止。备份交给浏览器下载，请确认文件已保存。</p></details>
 <button className="primary" disabled={busy} onClick={()=>void remove(true)}><Icon name="download" size={17}/>{busy?'正在处理…':'导出备份并移入回收站'}</button>
 <div className="workspace-delete-actions"><button disabled={busy} onClick={()=>setTarget(undefined)}>取消</button><button className="quiet-danger" disabled={busy} onClick={()=>void remove(false)}>不导出，移入回收站</button></div>
 </section>:<>
 <div className="panel-tabs" role="tablist" aria-label="工作台列表"><button role="tab" aria-selected={!showTrash} onClick={()=>setShowTrash(false)}>工作台</button><button role="tab" aria-selected={showTrash} onClick={()=>setShowTrash(true)}>回收站 <span>{trash.length}</span></button></div>
 {showTrash&&trash.length>0&&<p className="trash-description">恢复到工作台，或永久移除不再需要的内容。</p>}
 <div className="workspace-list" role="tabpanel" aria-label={showTrash?'回收站':'工作台'}>{[...(showTrash?trash:all)].sort((a,b)=>b.updatedAt-a.updatedAt).map(p=><div className={`workspace-row ${showTrash?'trashed':p.id===current?'current':''}`} key={p.id}>{showTrash?<><div className="workspace-trashed"><Icon name="board" size={20}/><span><strong>{p.boards[p.rootId].title}</strong><small>{Object.keys(p.boards).length} 张画板 · {date(p)}</small></span></div><div className="trash-row-actions"><button className="workspace-restore" disabled={readOnly||busy} onClick={()=>void restore(p)}>恢复</button><button className="workspace-purge-one" title={`永久删除：${p.boards[p.rootId].title}`} disabled={readOnly||busy} onClick={()=>setPurge({ids:[p.id],title:`永久删除「${p.boards[p.rootId].title}」？`})}><Icon name="trash" size={17}/></button></div></>:<><button className="workspace-open" aria-current={p.id===current?'true':undefined} onClick={()=>onSwitch(p)}><Icon name="board"/><span><strong>{p.boards[p.rootId].title}</strong><small>{Object.keys(p.boards).length} 张画板 · {date(p)}</small></span></button><button className="workspace-remove" title={`删除工作台：${p.boards[p.rootId].title}`} disabled={readOnly} onClick={()=>setTarget(p.id===current?activeProject:p)}><Icon name="trash" size={17}/></button></>}</div>)}{showTrash&&!trash.length&&<div className="workspace-empty"><Icon name="trash" size={26}/><strong>回收站是空的</strong><span>移除的工作台会出现在这里。</span></div>}</div>
 <div className="workspace-controls">{showTrash?<><span className="panel-footnote">共 {trash.length} 个工作台</span><button className="clear-trash" disabled={readOnly||busy||!trash.length} onClick={()=>setPurge({ids:trash.map(p=>p.id),title:'彻底清除回收站？'})}><Icon name="trash" size={16}/>清除回收站</button></>:<><button className="soft-button" disabled={readOnly} onClick={onNew}><Icon name="plus" size={16}/>新建工作台</button><span className="panel-footnote">数据保存在本浏览器</span></>}</div>
 </>}</section>;
}
